# Generated by Django 4.0.2 on 2022-02-05 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedMarker',
            fields=[
                ('marker_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='markers.marker')),
            ],
            options={
                'verbose_name': 'přijatý bod',
                'verbose_name_plural': 'přijaté body',
            },
            bases=('markers.marker',),
        ),
        migrations.CreateModel(
            name='MarkerProposal',
            fields=[
                ('marker_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='markers.marker')),
            ],
            options={
                'verbose_name': 'návrh bodu',
                'verbose_name_plural': 'návrhy bodů',
            },
            bases=('markers.marker',),
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'obrázek', 'verbose_name_plural': 'obrázky'},
        ),
        migrations.AlterModelOptions(
            name='marker',
            options={'verbose_name': 'bod', 'verbose_name_plural': 'body'},
        ),
    ]
