# Generated by Django 4.0.2 on 2022-02-05 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0002_acceptedmarker_markerproposal_alter_image_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='markerproposal',
            options={'permissions': [('accept_markerproposal', 'Může přijmout návrh bodu')], 'verbose_name': 'návrh bodu', 'verbose_name_plural': 'návrhy bodů'},
        ),
    ]
