# Generated by Django 4.0.2 on 2022-02-20 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0003_alter_markerproposal_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='marker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marker_images', to='markers.marker'),
        ),
    ]
