# Generated by Django 4.0.2 on 2022-02-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0004_alter_image_marker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='source_url',
            field=models.URLField(blank=True, default='', verbose_name='adresa zdroje'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='popis'),
        ),
    ]
